spring:
  application:
    name: poc-redis-cacheable
  cache:
    type: redis
    redis:
      time-to-live: 120000 # TTL padrão em milissegundos (aqui: 5 minutos)
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "meuapp::"  # Prefixo usado em todas as chaves de cache
  redis:
    host: localhost
    port: 6379
    timeout: 1s
    database: 0  # você pode trocar para 1, 2... se quiser separar ambientes
